name: Update Profile README

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run update script
        run: node index.ts
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
